=== Alonso532532/Dam1/LM/T6/Ejercicios/EjPractica/2/centro.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="tipoCurso">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"></xs:minInclusive>
            <xs:maxInclusive value="4"></xs:maxInclusive>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoTamaño">
        <xs:restriction base="xs:string">
            <xs:enumeration value="pequeña"></xs:enumeration>
            <xs:enumeration value="mediana"></xs:enumeration>
            <xs:enumeration value="grande"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="centro">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="profesorado">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="profesor" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="asignatura" type="xs:string"/>
                                        <xs:element name="edad" type="xs:integer" minOccurs="0"/>
                                    </xs:sequence>
                                    <xs:attribute name="clase" type="xs:IDREF"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="alumnado">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="alumno" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="curso" type="tipoCurso"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="instalaciones">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="clase" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="id" type="xs:ID"/>
                                    <xs:attribute name="tamaño" type="tipoTamaño"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Alonso532532/Dam1/LM/T6/Ejercicios/EjPractica/2/centro copy.xml
<?xml version="1.0" encoding="UTF-8"?>
<centro xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="centro.xsd">

    <profesorado>
        <profesor clase="C001">
            <nombre>Pablo</nombre>
            <asignatura>Geografia</asignatura>
        </profesor>
        <profesor clase="C002">
            <nombre>Miguel</nombre>
            <asignatura>Historia</asignatura>
            <edad>20</edad>
        </profesor>
    </profesorado>
    <alumnado>
        <alumno>
            <nombre>EKER</nombre>
            <curso>1</curso>
        </alumno>
        <alumno>
            <nombre>Lozan</nombre>
            <curso>2</curso>
        </alumno>
        <alumno>
            <nombre>Hproll</nombre>
            <curso>3</curso>
        </alumno>
        <alumno>
            <nombre>Tetico</nombre>
            <curso>4</curso>
        </alumno>
    </alumnado>
    <instalaciones>
        <clase id="C001" tamaño="pequeña"/>
        <clase id="C002" tamaño="grande"/>
        <clase id="C003" tamaño="mediana"/>
    </instalaciones>
</centro>
