=== Alonso532532/Dam1/LM/T6/Ejercicios/EjsModeloExamen/Ej2/val.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:simpleType name="tipoDificultad">

        <xs:restriction base="xs:string">
            <xs:enumeration value="facil"/>
            <xs:enumeration value="medio"/>
            <xs:enumeration value="dificil"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoTipo">
        <xs:restriction base="xs:string">
            <xs:enumeration value="basico"/>
            <xs:enumeration value="especiado"/>
            <xs:enumeration value="guarnicion"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="receta">
        <xs:complexType>
            <xs:sequence>
                
                <xs:element name="ingredientes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ingrediente" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="cantidad" type="xs:double"/>
                                        <xs:element name="unidad" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:ID"/>
                                    <xs:attribute name="tipo" type="tipoTipo" default="basico"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="elaboracion">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="paso" maxOccurs="unbounded" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="tiempoElaboracion" type="xs:integer"/>
                <xs:element name="etiqueta" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:attribute name="tipo" type="xs:string"/>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
            <xs:attribute name="codigo" type="xs:ID"/>
            <xs:attribute name="nombre" type="xs:string"/>
            <xs:attribute name="dificultad" type="tipoDificultad" use="optional"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Alonso532532/Dam1/LM/T6/Ejercicios/EjsModeloExamen/Ej2/receta2.xml
<?xml version="1.0" encoding="UTF-8"?>
<receta codigo="AL001" nombre="Patatas fritas" dificultad="facil" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="val.xsd">
    <ingredientes>
        <ingrediente id="ING001" tipo="basico">
            <nombre>Patatas</nombre>
            <cantidad>10</cantidad>
            <unidad>unidades</unidad>
        </ingrediente>
        <ingrediente id="ING002" tipo="basico">
            <nombre>Aceite</nombre>
            <cantidad>1</cantidad>
            <unidad>DcLitro</unidad>
        </ingrediente>
        <ingrediente id="ING003">
            <nombre>Macarrones</nombre>
            <cantidad>50</cantidad>
            <unidad>gramos</unidad>
        </ingrediente>
    </ingredientes>
    <elaboracion>
        <paso>
            Herbir en aceite
        </paso>
        <paso>
            Poner sal
        </paso>
    </elaboracion>
    <tiempoElaboracion>30</tiempoElaboracion>
</receta>

=== Alonso532532/Dam1/LM/T6/Ejercicios/EjsModeloExamen/Ej2/receta3.xml
<?xml version="1.0" encoding="UTF-8"?>
<receta codigo="AL001" nombre="Bocadillo de rufles" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="val.xsd">
    <ingredientes>
        <ingrediente id="ING001" tipo="basico">
            <nombre>Rufles (Jamon)</nombre>
            <cantidad>50</cantidad>
            <unidad>unidades</unidad>
        </ingrediente>
        <ingrediente id="ING002" tipo="basico">
            <nombre>Barrapan</nombre>
            <cantidad>1</cantidad>
            <unidad>unidad</unidad>
        </ingrediente>
    </ingredientes>
    <elaboracion>
        <paso>
            Abres el pan y las rufles
        </paso>
        <paso>
            Poner cosas
        </paso>
    </elaboracion>
    <tiempoElaboracion>15</tiempoElaboracion>
    <etiqueta tipo="Eker"></etiqueta>
</receta>

=== Alonso532532/Dam1/LM/T6/Ejercicios/EjsModeloExamen/Ej2/receta.xml
<?xml version="1.0" encoding="UTF-8"?>
<receta codigo="AL001" nombre="Macarrones" dificultad="facil" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="val.xsd">
    <ingredientes>
        <ingrediente id="ING001" tipo="basico">
            <nombre>Macarrones</nombre>
            <cantidad>50</cantidad>
            <unidad>unidades</unidad>
        </ingrediente>
        <ingrediente id="ING002" tipo="basico">
            <nombre>tomate</nombre>
            <cantidad>20</cantidad>
            <unidad>gramos</unidad>
        </ingrediente>
        <ingrediente id="ING003" tipo="basico">
            <nombre>queso</nombre>
            <cantidad>15</cantidad>
            <unidad>gramos</unidad>
        </ingrediente>
    </ingredientes>
    <elaboracion>
        <paso>
            Herbir en agua
        </paso>
        <paso>
            Poner cosas
        </paso>
        <paso>
            Disfrutar
        </paso>
    </elaboracion>
    <tiempoElaboracion>45</tiempoElaboracion>
    <etiqueta tipo="pasta"></etiqueta>
    <etiqueta tipo="mu gueno"></etiqueta>
</receta>
