=== Alonso532532/Dam1/LM/T6/Ejercicios/Ej4/restaurante.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="tipoAlergeno">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Melocoton"/>
            <xs:enumeration value="Gluten"/>
            <xs:enumeration value="Queso"/>
            <xs:enumeration value="Olivas"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="menu">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="entrantes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="plato" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="descripcion" type="xs:string"/>
                                        <xs:element name="precio" type="xs:double"/>
                                        <xs:element name="cocina">
                                            <xs:complexType>
                                                <xs:attribute name="id" type="xs:ID"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="alergenos" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="alergeno" type="tipoAlergeno" maxOccurs="unbounded"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="codPlato" type="xs:ID"/>
                                    <xs:attribute name="nombreMenu" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="principales">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="plato" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="descripcion" type="xs:string"/>
                                        <xs:element name="precio" type="xs:double"/>
                                        <xs:element name="cocina">
                                            <xs:complexType>
                                                <xs:attribute name="id" type="xs:ID"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="alergenos" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="alergeno" type="tipoAlergeno" maxOccurs="unbounded"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="codPlato" type="xs:ID"/>
                                    <xs:attribute name="nombreMenu" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="postres">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="plato" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="descripcion" type="xs:string"/>
                                        <xs:element name="precio" type="xs:double"/>
                                        <xs:element name="cocina">
                                            <xs:complexType>
                                                <xs:attribute name="id" type="xs:ID"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="alergenos" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="alergeno" type="tipoAlergeno" maxOccurs="unbounded"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="codPlato" type="xs:ID"/>
                                    <xs:attribute name="nombreMenu" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Alonso532532/Dam1/LM/T6/Ejercicios/Ej4/restaurante copy.xml
<?xml version="1.0" encoding="UTF-8"?>
<menu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="restaurante.xsd">
    <entrantes>
        <plato codPlato="A001" nombreMenu="Iker lozano romero">
            <nombre>Ensalada</nombre>
            <descripcion>Cosas verdes</descripcion>
            <precio>12.50</precio>
            <cocina id="C001"/>
            <alergenos>
                <alergeno>Melocoton</alergeno>
                <alergeno>Gluten</alergeno>
            </alergenos>
        </plato>
    </entrantes>
    <principales>
        <plato codPlato="A002" nombreMenu="Macarrones carbonara">
            <nombre>Macarrones</nombre>
            <descripcion>Imprescindible</descripcion>
            <precio>14.5</precio>
            <cocina id="C002"/>
            <alergenos>
                <alergeno>Gluten</alergeno>
            </alergenos>
        </plato>
    </principales>
    <postres>
        <plato codPlato="A003">
            <nombre>Tarta de queso</nombre>
            <descripcion>TOP</descripcion>
            <precio>9.2</precio>
            <cocina id="C003"/>
            <alergenos>
                <alergeno>Queso</alergeno>
            </alergenos>
        </plato>
        <plato codPlato="A004" nombreMenu="Frigopie">
            <nombre>HELAO</nombre>
            <descripcion>Si</descripcion>
            <precio>8.2</precio>
            <cocina id="C004"/>
        </plato>
    </postres>
</menu>
