=== Alonso532532/Dam1/LM/T6/Ejercicios/EjPractica/1/file.dtd
<!ELEMENT Biblioteca (libro+, autor+)>
    <!ELEMENT libro (titulo, año, autorref)>
        <!ELEMENT titulo (#PCDATA)>
        <!ELEMENT año (#PCDATA)>
        <!ELEMENT autorref (#PCDATA)>
        <!ATTLIST autorref id IDREF #REQUIRED>
    <!ELEMENT autor (nombre)>
    <!ATTLIST autor id ID #REQUIRED>
        <!ELEMENT nombre (#PCDATA)>

=== Alonso532532/Dam1/LM/T6/Ejercicios/EjPractica/1/libros.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Biblioteca SYSTEM "file.dtd">
<Biblioteca>
    <libro>
        <titulo>EKR</titulo>
        <año>2004</año>
        <autorref id="A001"></autorref>
    </libro>
    <libro>
        <titulo>HECPROLL</titulo>
        <año>2007</año>
        <autorref id="A002"></autorref>
    </libro>
    <autor id="A001">
        <nombre>Alonso</nombre>
    </autor>
    <autor id="A002">
        <nombre>Pascual</nombre>
    </autor>
</Biblioteca>

=== Alonso532532/Dam1/LM/T6/Ejercicios/EjPractica/libros.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Biblioteca SYSTEM "file.dtd">
<Biblioteca>
    <libro>
        <titulo>EKR</titulo>
        <año>2004</año>
        <autorref id="A001"></autor>
    </libro>
    <libro>
        <titulo>HECPROLL</titulo>
        <año>2007</año>
        <autorref id="A002"></autor>
    </libro>
    <autor id="A001">
        <nombre>Alonso</nombre>
    </autor>
    <autor id="A002">
        <nombre>Pascual</nombre>
    </autor>
</Biblioteca>
