=== Alonso532532/Dam1/LM/T6/Ejercicios/Ej2/empresa.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="empresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="departamentos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="departamento" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="ubicacion" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:ID"/>
                                    <xs:attribute name="codigo" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="empleados">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="empleado" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="apellido" type="xs:string"/>
                                        <xs:element name="fechaNcto" type="xs:string"/>
                                        <xs:element name="departamentoRef">
                                            <xs:complexType>
                                                <xs:attribute name="refDep" type="xs:IDREF"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="dni" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Alonso532532/Dam1/LM/T6/Ejercicios/Ej2/empresa copy.xml
<?xml version="1.0" encoding="UTF-8"?>

<empresa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="empresa.xsd">
    <departamentos>
        <departamento id="E01" codigo="YEAH">
            <nombre></nombre>
            <ubicacion></ubicacion>
        </departamento>
    </departamentos>
    <empleados>
        <empleado dni="DNI131231S">
            <nombre>asas</nombre>
            <apellido>asdad</apellido>
            <fechaNcto>asda</fechaNcto>            
            <departamentoRef refDep="E01"/>
        </empleado>
    </empleados>
</empresa>
